### ISSUE TITLE
Issue with Netlify Deployment

### ISSUE THREAD

**Issue by bastianhilton** [openshiporg/openship#19]
Good afternoon, when attempting to deploy to Netlify, i'm getting the following error message:

2:38:50 PM: build-image version: 8fa244c78cd67d8b6f2fa49817cac5c730095600 (focal)
2:38:50 PM: buildbot version: ffe65ff6df272d8339700be586c63030d957782b
2:38:50 PM: Fetching cached dependencies
2:38:50 PM: Failed to fetch cache, continuing with build
2:38:50 PM: Starting to prepare the repo for build
2:38:51 PM: No cached dependencies found. Cloning fresh repo
2:38:51 PM: git clone --filter=blob:none https://github.com/**respositoryname**/openship
2:38:51 PM: Preparing Git Reference refs/heads/main
2:38:52 PM: Failing build: Failed to parse configuration
2:38:52 PM: Finished processing build request in 1.927s
2:38:52 PM: Failed during stage "Reading and parsing configuration files": 
When resolving config file /opt/build/repo/netlify.toml:
Could not parse configuration file
Expected """, """"", "+", "-", "[", "\"", "\"\"\"", "_", "false", "true", "{", [ \t] or [0-9] but "$" found.

: exit status 1

_Repositoryname has an actual name its just omitted from this code._

**Comment by junaid33** [comment]
It looks like Netlify.toml is not needed and the format has changed. I've deleted it so please try the Netlify deploy button again. Also the build will fail initially because Netlify doesn't let you set environmental variables before deployment. Be sure to add FRONTEND_URL, DATABASE_URL, and SESSION_SECRET in the Netlify UI and redeploy.
